name: nutri_mate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.0
  collection: ^1.19.1
  csv: ^6.0.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  intl: ^0.20.2
  pay: ^3.2.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/burgers/
    - lib/images/desserts/
    - lib/images/salads/
    - lib/images/sides/
    - lib/images/tiffin/
    - lib/images/lunch/
    - lib/images/dinner/
    - lib/images/snacks/
    - lib/images/default/
    - lib/images/onboarding/
    - assets/payments/gpay_config.json
    - assets/data/
    - assets/data/disease_food_recommendations_v2.csv
